// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChirpItemComponent: typeof import('./src/components/Chirp/ChirpItemComponent.vue')['default']
    ChirpListComponent: typeof import('./src/components/Chirp/ChirpListComponent.vue')['default']
    ChirpPanelComponent: typeof import('./src/components/Chirp/ChirpPanelComponent.vue')['default']
    LinkComponent: typeof import('./src/components/LinkComponent.vue')['default']
    NavigationPanelComponent: typeof import('./src/components/NavigationPanelComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInputComponent: typeof import('./src/components/SearchInputComponent.vue')['default']
    TrendingItemComponent: typeof import('./src/components/Trending/TrendingItemComponent.vue')['default']
    TrendingPanelComponent: typeof import('./src/components/Trending/TrendingPanelComponent.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}
