// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BCard: typeof import('bootstrap-vue')['BCard']
    BImg: typeof import('bootstrap-vue')['BImg']
    BMedia: typeof import('bootstrap-vue-next')['BMedia']
    ChirpList: typeof import('./src/components/ChirpList.vue')['default']
    HelloWorld: typeof import('./src/pages/ChirpList.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    ProfileSidePanelComponent: typeof import('./src/components/ProfileSidePanelComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tweet: typeof import('./src/components/Tweet.vue')['default']
    TweetComponent: typeof import('./src/components/TweetComponent.vue')['default']
  }
}
