// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BCard: typeof import('bootstrap-vue')['BCard']
    BImg: typeof import('bootstrap-vue')['BImg']
    BMedia: typeof import('bootstrap-vue-next')['BMedia']
    ChirpComponent: typeof import('./src/components/ChirpComponent.vue')['default']
    ChirpItemComponent: typeof import('./src/components/Chirp/ChirpItemComponent.vue')['default']
    ChirpList: typeof import('./src/components/Chirp/ChirpList.vue')['default']
    ChirpListComponent: typeof import('./src/components/Chirp/ChirpListComponent.vue')['default']
    ChirpPanelComponent: typeof import('./src/components/Chirp/ChirpPanelComponent.vue')['default']
    HelloWorld: typeof import('./src/pages/ChirpList.vue')['default']
    HomeChirpList: typeof import('./src/components/Chirp/HomeChirpList.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    ProfileSidePanelComponent: typeof import('./src/components/ProfileSidePanelComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrendingItemComponent: typeof import('./src/components/Trending/TrendingItemComponent.vue')['default']
    TrendingPanelComponent: typeof import('./src/components/Trending/TrendingPanelComponent.vue')['default']
    Tweet: typeof import('./src/components/Tweet.vue')['default']
    TweetComponent: typeof import('./src/components/ChirpComponent.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}
